config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :policies, only: [:new, :create]

  resource :charges, only: [:new, :create] do
    get '/success', to:'charges#success'
    get '/cancel', to:'charges#cancel'
  end

  get '/new_policies', to: 'policies#new'
  post '/create_policies', to: 'policies#create'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :username, presence: true
  validates :password_digest, presence: true, length: { minimum: 3, maximum: 20 }, unless: :login_with_provider?

  def login_with_provider?
    provider.present?
  end

  def authenticate(unencrypted_password)
    BCrypt::Password.new(password_digest).is_password?(unencrypted_password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def required_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end

  def logged_in?
    current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # JWT_SECRET_KEY = Rails.application.secrets.secret_key_base.to_s
  #TODO colocar expiração por tempo
  def encode
    JWT.encode({}, ENV['JWT_SECRET_KEY'], 'HS256')
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    render 'charges/new'
  end
  
  def success
    #handle successful charges
    render 'charges/success', notice: "Compra bem sucedida!"
  end
  
  def cancel
    #handle if the charge is cancelled
    render 'charges/cancel', notice: "Falha no processo de compra."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    required_login

    @policies = policies(request_graphql)
  end

  private

  def policies(response_body)
    response_body&.dig(:data, :policies)
  end

  def request_graphql
    url = URI("http://web:3003/graphql")
    headers = {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{encode}"
    }
    body = { query: body_builder }.to_json

    response = Net::HTTP.post(url, body, headers)
    responsed_body = JSON.parse(response.body, symbolize_names: true)
  rescue
    nil
  end

  def body_builder
    <<-GRAPHQL
      query {
        policies(limit: null) {
            id
            dateIssue
            policyExpiration
            status
            insured {
                id
                name
                cpf
            }
            vehicle {
                id
                licensePlate
                year
                model
                brand
            }
            charge {
              id
              paymentId
              paymentLink
            }
        }
      }
    GRAPHQL
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  include Requester

  def new
  end

  def create
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        price: 'price_1PDsdHFAZsZguLCRZjU1gwDt',
        quantity: 1,
      }],
      mode: 'payment',
      success_url:  success_charges_url,
      cancel_url: cancel_charges_url
    )

    policy = policy_params
    policy[:payment_id] = session.id
    policy[:payment_link] = session.url

    headers = {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{encode}"
    }
    body = body_builder(policy).to_json
    url = URI("http://web:3003/graphql")

    response = Requester.send_request(headers, body, url)
    responsed_body = JSON.parse(response.body, symbolize_names: true)

    if responsed_body[:data][:createPolicy][:result] == 'OK'
      flash[:alert] = "Policy created successfully!!"
      redirect_to root_path
    end
  rescue
    #TODO melhorar o rescue
    flash.now[:notice] = "Error"
  end

  def policy_params
    params.require(:policy).permit(
      :insured_name,
      :insured_cpf,
      :date_issue,
      :policy_expiration,
      :license_plate,
      :brand,
      :model,
      :year
    )
  end

  def body_builder(policy)
    {
      query: "mutation {
        createPolicy(
        input: {
            policy: {
                dateIssue: \"#{policy[:date_issue]}\",
                policyExpiration: \"#{policy[:policy_expiration]}\",
                insured: {
                    name: \"#{policy[:insured_name]}\",
                    cpf: \"#{policy[:insured_cpf]}\",
                },
                vehicle: {
                    licensePlate: \"#{policy[:license_plate]}\",
                    brand: \"#{policy[:brand]}\",
                    model: \"#{policy[:model]}\",
                    year: \"#{policy[:year]}\"
                },
                charge: {
                  paymentId: \"#{policy[:payment_id]}\",
                  paymentLink: \"#{policy[:payment_link]}\",
                },
            }
        }
         ) { result }
      }"
    }
  end

  #TODO fazer usando variáveis
  # {
  #   query: "
  #     mutation createPolicy(
  #       $dateIssue: String!
  #       $policyExpiration: String!
  #       $name: String!
  #       $cpf: String!
  #       $licensaPlate: String!
  #       $brand: String!
  #       $model: String!
  #       $year: String!
  #     )
  #     {
  #       createPolicy (
  #         input: {
  #           policy: {
  #             dateIssue: $dateIssue,
  #             policyExpiration: $policyExpiration
  #             insured: {
  #               name: $name,
  #               cpf: $cpf
  #             },
  #             vehicle: {
  #               licensaPlate: $licensaPlate,
  #               brand: $brand,
  #               model: $model,
  #               year: $year
  #             }
  #           }
  #         }
  #       )
  #     }
  #   ",
  #   variables: {
  #     dateIssue: policy[:date_issue],
  #     policyExpiration: policy[:policy_expiration],
  #     name: policy[:insured_name],
  #     cpf: policy[:insured_cpf],
  #     licensaPlate: policy[:license_plate],
  #     brand: policy[:brand],
  #     model: policy[:model],
  #     year: policy[:year]
  #   }
  # }
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      redirect_to root_path
    else
      flash[:error] = 'Invalid username or password'
      redirect_to login_path
    end
  end

  def omniauth
    @user = User.find_or_create_by(uid: omniauth_auth['uid'], provider: omniauth_auth['provider']) do |u|
      u.email = omniauth_auth.dig('info', 'email')
      u.username = omniauth_auth.dig('info', 'name') || u.email
    end

    if @user.valid?
      session[:user_id] = @user.id

      redirect_to root_path
    else
        render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  attr_reader :omniauth_auth

  def omniauth_auth
    @omniauth_auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/home/index.html.erb
<h1> Welcome <%= @current_user.username %>! </h1>
<%= button_to "Create new policy", new_policies_path, method: :get %>
<%= button_to "Logout", logout_path, method: :delete %>

<% if @policies%>
    <h2>Policies Created</h2>
    <table class='table' border="1">
        <tr>
            <td>Policy Start</td>
            <td>Policy Finish</td>
            <td>Insured</td>
            <td>Car Model</td>
            <td>Status</td>
            <td>Payment Link</td>
        </tr>
        <% @policies.each do |policy| %>
        <tr>
            <td><%= policy[:dateIssue] %></td>
            <td><%= policy[:policyExpiration] %></td>
            <td><%= policy[:insured][:name] %></td>
            <td><%= policy[:vehicle][:model] %></td>
            <td><%= policy[:status] %></td>
            <td style="max-width: 200px; overflow: hidden;">
                <a href="<%= policy[:charge][:paymentLink] %>" target="_blank"> Link to pay</a>
            </td>

        </tr>
        <% end %>
    </table>
<% else %>
    <h2> No policy found! </h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsOnWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/policies/new.html.erb
<h2>New Policy</h2>
<div style="margin: 0px auto; max-width: 720px;" class="container">

<%= form_with scope: :policy, url: create_policies_path, data: {turbo: false} do |form| %>
    <div>
      <%= form.label :insured_name, 'Insured Name:', class: 'label' %>
      <%= form.text_field :insured_name, required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :insured_cpf, 'Insured CPF:' %>
      <%= form.text_field :insured_cpf, required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :date_issue, 'Policy Start in:', class: 'label' %>
      <%= form.date_field :date_issue,required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :policy_expiration, 'Policy Finish in:', class: 'label' %>
      <%= form.date_field :policy_expiration,required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :license_plate, 'License Plate:', class: 'label' %>
      <%= form.text_field :license_plate, required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :brand, 'Car Brand:', class: 'label' %>
      <%= form.text_field :brand, required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :model, 'Car Model:', class: 'label' %>
      <%= form.text_field :model, required: true, class: 'input' %>
    </div>

    <div>
      <%= form.label :year, 'Car Year:', class: 'label' %>
      <%= form.number_field :year, required: true, class: 'input' %>
    </div>

    <div>
      <br />
      <%= form.submit 'Create Policy', class: 'button is-link' %>
    </div>
<% end %>

<%= button_to 'Home', root_path, method: :get, data: { turbo: false } %>
    </div>

app/views/users/new.html.erb
<h1> Sign up for a new account </h1>
<%= form_with scope: :user, url: '/signup', method: :post do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign up" %>
<% end %>

<p>Already have an account? <%= link_to "Login", login_path %></p>